language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mm88code/server_grider-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mm88code/server_grider-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'server_grider-docker-react'
  env: 'ServerGriderDockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-123154316821'
  bucket_path: 'server_grider-docker-react'
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: '$AWS_SECRET_KEY'
